package com.tool.plaform.dao;

import com.tool.plaform.entity.User;
import com.tool.plaform.entity.UserQuery;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    User queryUserByLoginName(UserQuery userQuery);
}