package com.tool.plaform.entity;

public class Api {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.id
     *
     * @mbg.generated
     */
    private Integer id;

    private String rooturl;

    public String getRooturl() {
        return rooturl;
    }

    public void setRooturl(String rooturl) {
        this.rooturl = rooturl;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.param
     *
     * @mbg.generated
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.contenttype
     *
     * @mbg.generated
     */
    private String contenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.expect
     *
     * @mbg.generated
     */
    private String expect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.id
     *
     * @return the value of api.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.id
     *
     * @param id the value for api.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.method
     *
     * @return the value of api.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.method
     *
     * @param method the value for api.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.url
     *
     * @return the value of api.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.url
     *
     * @param url the value for api.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.param
     *
     * @return the value of api.param
     *
     * @mbg.generated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.param
     *
     * @param param the value for api.param
     *
     * @mbg.generated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.type
     *
     * @return the value of api.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.type
     *
     * @param type the value for api.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.contenttype
     *
     * @return the value of api.contenttype
     *
     * @mbg.generated
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.contenttype
     *
     * @param contenttype the value for api.contenttype
     *
     * @mbg.generated
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.expect
     *
     * @return the value of api.expect
     *
     * @mbg.generated
     */
    public String getExpect() {
        return expect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.expect
     *
     * @param expect the value for api.expect
     *
     * @mbg.generated
     */
    public void setExpect(String expect) {
        this.expect = expect == null ? null : expect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.port
     *
     * @return the value of api.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.port
     *
     * @param port the value for api.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}