package com.tool.plaform.entity;

import java.util.Date;

public class Rule {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.cond
     *
     * @mbg.generated
     */
    private String cond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.cond_content
     *
     * @mbg.generated
     */
    private String condContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.fields
     *
     * @mbg.generated
     */
    private String fields;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.cond
     *
     * @return the value of rule.cond
     *
     * @mbg.generated
     */
    public String getCond() {
        return cond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.cond
     *
     * @param cond the value for rule.cond
     *
     * @mbg.generated
     */
    public void setCond(String cond) {
        this.cond = cond == null ? null : cond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.cond_content
     *
     * @return the value of rule.cond_content
     *
     * @mbg.generated
     */
    public String getCondContent() {
        return condContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.cond_content
     *
     * @param condContent the value for rule.cond_content
     *
     * @mbg.generated
     */
    public void setCondContent(String condContent) {
        this.condContent = condContent == null ? null : condContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.fields
     *
     * @return the value of rule.fields
     *
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.fields
     *
     * @param fields the value for rule.fields
     *
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.result_field
     *
     * @mbg.generated
     */
    private String resultField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.inner_description
     *
     * @mbg.generated
     */
    private String innerDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.outer_description
     *
     * @mbg.generated
     */
    private String outerDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.id
     *
     * @return the value of rule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.id
     *
     * @param id the value for rule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.name
     *
     * @return the value of rule.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.name
     *
     * @param name the value for rule.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.desc
     *
     * @return the value of rule.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.desc
     *
     * @param desc the value for rule.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.result
     *
     * @return the value of rule.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.result
     *
     * @param result the value for rule.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.result_field
     *
     * @return the value of rule.result_field
     *
     * @mbg.generated
     */
    public String getResultField() {
        return resultField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.result_field
     *
     * @param resultField the value for rule.result_field
     *
     * @mbg.generated
     */
    public void setResultField(String resultField) {
        this.resultField = resultField == null ? null : resultField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.state
     *
     * @return the value of rule.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.state
     *
     * @param state the value for rule.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.created_at
     *
     * @return the value of rule.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.created_at
     *
     * @param createdAt the value for rule.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.updated_at
     *
     * @return the value of rule.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.updated_at
     *
     * @param updatedAt the value for rule.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.operator
     *
     * @return the value of rule.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.operator
     *
     * @param operator the value for rule.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.inner_description
     *
     * @return the value of rule.inner_description
     *
     * @mbg.generated
     */
    public String getInnerDescription() {
        return innerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.inner_description
     *
     * @param innerDescription the value for rule.inner_description
     *
     * @mbg.generated
     */
    public void setInnerDescription(String innerDescription) {
        this.innerDescription = innerDescription == null ? null : innerDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.outer_description
     *
     * @return the value of rule.outer_description
     *
     * @mbg.generated
     */
    public String getOuterDescription() {
        return outerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.outer_description
     *
     * @param outerDescription the value for rule.outer_description
     *
     * @mbg.generated
     */
    public void setOuterDescription(String outerDescription) {
        this.outerDescription = outerDescription == null ? null : outerDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.remark
     *
     * @return the value of rule.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.remark
     *
     * @param remark the value for rule.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

}